name: Deploy slides to GitHub Pages
on:
  push:
    paths:
      - "slides/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install & Build Positioning
        working-directory: ./slides/positioning
        run: |
          yarn install
          yarn build -o ../../dist/positioning --base /smart-car-auto-parking/positioning
      - name: Install & Build Parking
        working-directory: ./slides/parking
        run: |
          yarn install
          yarn build -o ../../dist/parking --base /smart-car-auto-parking/parking
      - name: Install & Build streaming
        working-directory: ./slides/streaming
        run: |
          yarn install
          yarn build -o ../../dist/streaming --base /smart-car-auto-parking/streaming
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
